title: Unsong
author: Scott Alexander
filename: unsong
base_url: "http://unsongbook.com"
toc_url: "http://unsongbook.com"
toc_regex: unsongbook[^\?]*(interlude|chapter|prolog|book|epilog|arc)[^#]*$
title_path: ".pjgm-posttitle"
content_path: ".pjgm-postcontent"
garbage_path: ".//div[@class='sharedaddy sd-sharing-enabled']"
chapter_title_format: '<h1 class="chapter_title">%s</h1>'
